### ISSUE TITLE
Install Elasticsearch to use ebextensions config file

### ISSUE THREAD

**Issue by FullStackerWeb** [xrnm/rails-elastic-beanstalk#2]
I am going to install elasticsearch on AWS Elastic Beanstalk to use ebextensions.

I'd like you to let me know how can I install elasticsearch on that with ebextensions config file.
Regards.

**Comment by xrnm** [comment]
I haven't ever done exactly that. There's no reason you couldn't add logic to install elasticsearch locally on the "leader" node and configure the others to talk to that node. Or, if you're using AWS ElasticSearch service you should be able to setup a cluster there and just add the configurations into application.yml
